"""Compliance report generation service (function 8).

Gathers live telemetry, derives control status against NIST CSF / CIS / GDPR
and renders HTML (Jinja2) or PDF (fpdf2) reports.
"""

import logging
from datetime import datetime, timezone

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.alert import Alert
from app.models.case import Case, CaseStatus
from app.models.data_source import DataSource
from app.services.report_templates import TEMPLATES, Control, build_controls

log = logging.getLogger("siem.reports")

_TEMPLATE_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{{ title }}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a2e; }
  h1 { color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 8px; }
  h2 { color: #0f3460; margin-top: 30px; }
  .meta { color: #555; font-size: 13px; margin-bottom: 24px; }
  table { border-collapse: collapse; width: 100%; margin-top: 12px; }
  th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #0f3460; color: #fff; }
  tr:nth-child(even) { background: #f4f6fb; }
  .status { font-weight: 600; text-transform: capitalize; }
  .implemented { color: #0f7b2e; }
  .partial { color: #b07400; }
  .not_implemented { color: #b02a37; }
  .metric { display: inline-block; background:#eef2fb; border:1px solid #d4ddf5; border-radius:6px;
            padding:10px 16px; margin:6px 8px 6px 0; }
  .metric b { display:block; font-size:20px; color:#0f3460; }
  .metric span { font-size:12px; color:#555; }
  .footer { margin-top: 40px; font-size: 11px; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }
</style>
</head>
<body>
  <h1>{{ title }}</h1>
  <div class="meta">Framework: {{ framework }} &nbsp;|&nbsp; Generated: {{ generated_at }} &nbsp;|&nbsp; Period: {{ period }} &nbsp;|&nbsp; Organization: {{ org }}</div>

  <h2>Executive metrics</h2>
  <div>
    {% for key, label in metric_labels %}
    <div class="metric"><b>{{ metrics[key] }}</b><span>{{ label }}</span></div>
    {% endfor %}
  </div>

  <h2>Control assessment</h2>
  <table>
    <tr><th>Control</th><th>Status</th><th>Description</th><th>Evidence</th></tr>
    {% for c in controls %}
    <tr>
      <td><b>{{ c.id }}</b><br/>{{ c.title }}</td>
      <td class="status {{ c.status }}">{{ c.status.replace('_', ' ') }}</td>
      <td>{{ c.description }}</td>
      <td>{{ c.evidence }}</td>
    </tr>
    {% endfor %}
  </table>

  {% if alerts %}
  <h2>Alert register</h2>
  <table>
    <tr><th>Rule</th><th>Severity</th><th>Status</th><th>Count</th></tr>
    {% for a in alerts %}
    <tr><td>{{ a.rule_title }}</td><td>{{ a.severity }}</td><td>{{ a.status }}</td><td>{{ a.count }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}

  <div class="footer">Auto-generated by the SIEM Platform compliance reporting module.</div>
</body>
</html>
"""


class ReportService:
    def __init__(self, db: Session) -> None:
        self.db = db

    # ------------------------------------------------------------- telemetry
    def _metrics(self) -> dict:
        total_alerts = self.db.scalar(select(func.count(Alert.id))) or 0
        open_alerts = (
            self.db.scalar(
                select(func.count(Alert.id)).where(Alert.status == "open")
            )
            or 0
        )
        total_cases = self.db.scalar(select(func.count(Case.id))) or 0
        resolved_cases = (
            self.db.scalar(select(func.count(Case.id)).where(Case.status == CaseStatus.RESOLVED))
            or 0
        )
        sources = list(self.db.scalars(select(DataSource)).all())
        active = [s for s in sources if s.enabled]
        return {
            "active_sources": len(active),
            "total_sources": len(sources),
            "total_alerts": total_alerts,
            "open_alerts": open_alerts,
            "total_cases": total_cases,
            "resolved_cases": resolved_cases,
            "detectors": 5,
            "events_stored": 0,
            "retention_days": settings.retention_delete_days,
        }

    def _alerts(self, limit: int = 200) -> list[dict]:
        rows = self.db.scalars(
            select(Alert).order_by(Alert.last_seen_at.desc()).limit(limit)
        ).all()
        return [
            {
                "rule_title": a.rule_title,
                "severity": a.severity,
                "status": a.status,
                "count": a.count,
            }
            for a in rows
        ]

    def _cases(self, limit: int = 200) -> list[dict]:
        rows = self.db.scalars(
            select(Case).order_by(Case.updated_at.desc()).limit(limit)
        ).all()
        return [{"id": c.id, "title": c.title, "status": c.status, "severity": c.severity} for c in rows]

    # ------------------------------------------------------------- rendering
    def _context(self, template: str) -> tuple[dict, list[Control], str, str]:
        metrics = self._metrics()
        controls = build_controls(template, metrics)
        spec = TEMPLATES[template]
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        return metrics, controls, spec["title"], spec["framework"]

    def render_html(self, template: str, *, org: str = "Example Corp", period: str = "Current") -> str:
        from jinja2 import Template

        metrics, controls, title, framework = self._context(template)
        metric_labels = [
            ("active_sources", "Active log sources"),
            ("total_alerts", "Alerts"),
            ("open_alerts", "Open alerts"),
            ("total_cases", "Cases"),
            ("resolved_cases", "Resolved cases"),
            ("retention_days", "Retention (days)"),
        ]
        jinja = Template(_TEMPLATE_HTML)
        return jinja.render(
            title=title,
            framework=framework,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            period=period,
            org=org,
            metrics=metrics,
            metric_labels=metric_labels,
            controls=controls,
            alerts=self._alerts(),
        )

    def render_pdf(self, template: str, *, org: str = "Example Corp", period: str = "Current") -> bytes:
        from fpdf import FPDF

        metrics, controls, title, framework = self._context(template)

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_x(10)
        pdf.set_font("helvetica", "B", 16)
        pdf.multi_cell(0, 10, title)
        pdf.set_x(10)
        pdf.set_font("helvetica", "", 9)
        pdf.multi_cell(0, 6, f"Framework: {framework}  |  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  |  Period: {period}  |  Org: {org}")
        pdf.ln(4)

        metric_labels = [
            ("active_sources", "Active log sources"),
            ("total_alerts", "Alerts"),
            ("open_alerts", "Open alerts"),
            ("total_cases", "Cases"),
            ("resolved_cases", "Resolved cases"),
            ("retention_days", "Retention (days)"),
        ]
        pdf.set_x(10)
        pdf.set_font("helvetica", "B", 11)
        pdf.multi_cell(0, 8, "Executive metrics")
        for key, label in metric_labels:
            pdf.set_x(10)
            pdf.set_font("helvetica", "", 9)
            pdf.multi_cell(0, 6, f"{label}: {metrics[key]}")
        pdf.ln(4)

        pdf.set_x(10)
        pdf.set_font("helvetica", "B", 11)
        pdf.multi_cell(0, 8, "Control assessment")
        for control in controls:
            pdf.set_x(10)
            pdf.set_font("helvetica", "B", 9)
            pdf.multi_cell(0, 6, f"{control.id}  {control.title}  [{control.status.replace('_', ' ')}]")
            pdf.set_x(10)
            pdf.set_font("helvetica", "", 8)
            pdf.multi_cell(0, 4, control.description)
            pdf.set_x(10)
            pdf.set_text_color(120, 120, 120)
            pdf.multi_cell(0, 4, f"Evidence: {control.evidence}")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

        return bytes(pdf.output())
