"""create users table

Revision ID: 44d8c93a4d6c
Revises: 
Create Date: 2026-08-01 14:12:23.668501
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '44d8c93a4d6c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
