"""add soar_actions table

Revision ID: 8a426d08d796
Revises: 5e61283207a4
Create Date: 2026-08-01 18:11:34.359373
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8a426d08d796'
down_revision: str | None = '5e61283207a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soar_actions',
    sa.Column('playbook_id', sa.String(length=128), nullable=False),
    sa.Column('playbook_name', sa.String(length=255), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soar_actions_alert_id'), 'soar_actions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_soar_actions_playbook_id'), 'soar_actions', ['playbook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soar_actions_playbook_id'), table_name='soar_actions')
    op.drop_index(op.f('ix_soar_actions_alert_id'), table_name='soar_actions')
    op.drop_table('soar_actions')
    # ### end Alembic commands ###
