"""add analyses table

Revision ID: 9a988941f2e3
Revises: 85354f27eb60
Create Date: 2026-08-01 17:30:49.421902
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9a988941f2e3'
down_revision: str | None = '85354f27eb60'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('mitre', sa.String(), nullable=True),
    sa.Column('recommended_actions', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_alert_id'), 'analyses', ['alert_id'], unique=False)
    op.create_index(op.f('ix_analyses_kind'), 'analyses', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_kind'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_alert_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
