"""Pydantic request models for the File Integrity Monitoring ingestion API.

Validation rules are strict on purpose - the server never trusts the agent:

- ``agent_code`` must be present and the ``X-API-Key`` header must match the
  registered agent before anything else runs.
- ``event_type`` is limited to the deterministic syscheck vocabulary.
- ``sha256`` must be exactly 64 lowercase/uppercase hex characters.
- ``path`` / ``old_path`` must be non-empty, free of control characters, and
  are normalized (never used to touch the local filesystem).
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator, model_validator

SHA256_RE = r"^[0-9a-fA-F]{64}$"

EVENT_TYPES = ("added", "modified", "deleted", "renamed")


def _validate_path(value: str, field_name: str) -> str:
    if not value or not value.strip():
        raise ValueError(f"{field_name} must not be empty")
    if len(value) > 1024:
        raise ValueError(f"{field_name} is too long (max 1024 chars)")
    if any(ord(ch) < 32 for ch in value):
        raise ValueError(f"{field_name} contains control characters")
    if "\x00" in value:
        raise ValueError(f"{field_name} contains a NUL byte")
    return value


class FimIngestRequest(BaseModel):
    """A single FIM event submitted by an enrolled endpoint agent."""

    agent_code: str = Field(..., min_length=1, max_length=64)
    event_type: Literal["added", "modified", "deleted", "renamed"]
    path: str = Field(..., min_length=1, max_length=1024)
    sha256: str | None = Field(default=None, pattern=SHA256_RE)
    size: int = Field(default=0, ge=0)
    modified_time: datetime | None = None
    user: str = Field(default="", max_length=64)
    user_id: str = Field(default="", max_length=128)
    owner: str | None = Field(default=None, max_length=128)
    permissions: str | None = Field(default=None, max_length=32)
    file_type: str | None = Field(default=None, max_length=32)
    old_sha256: str | None = Field(default=None, pattern=SHA256_RE)
    new_sha256: str | None = Field(default=None, pattern=SHA256_RE)
    old_path: str | None = Field(default=None, max_length=1024)
    source: str | None = Field(default=None, max_length=32)
    evidence: str | None = None
    # Stable per-change id generated by the agent; used for server-side dedupe.
    event_id: str | None = Field(default=None, max_length=64)

    @field_validator("path")
    @classmethod
    def _clean_path(cls, value: str) -> str:
        return _validate_path(value, "path")

    @field_validator("old_path")
    @classmethod
    def _clean_old_path(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _validate_path(value, "old_path")

    @model_validator(mode="after")
    def _check_event_consistency(self) -> "FimIngestRequest":
        if self.event_type in ("added", "modified") and not self.sha256:
            raise ValueError("sha256 is required for added/modified events")
        if self.event_type == "renamed" and not self.old_path:
            raise ValueError("old_path is required for renamed events")
        return self
